{
 "title": "Fake new Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Data Drift Monitoring for **Fake news Detection**\nUsing Evidently for data drift\n"
   }
  },
  {
   "title": "Dataset Drift",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "evidently:data_drift{key=\"dataset_drift\"}",
     "legendFormat": "dataset_drift"
    }
   ]
  },
  {
   "title": "Feature drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum(evidently:column_drift) by (key)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Share of drifted features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "evidently:data_drift{key=\"share_of_drifted_columns\"}",
     "legendFormat": "share"
    }
   ]
  },
  {
   "title": "Number of drifted feature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift{key=\"number_of_drifted_columns\"}",
     "legendFormat": "Drifted"
    }
   ]
  },
  {
   "title": "Total features",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift{key=\"number_of_columns\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}