datasets:
  fake_new_detection:
    column_mapping:
      categorical_features:
      - statement
      - venue
      - subject(s)
      - speaker
      - speaker's job title
      - state info
      - party affiliation
      - false counts
      - label
      numerical_features:
      - pants on fire counts
      - barely true counts
      - mostly true counts
      - half true counts
      target: cnt
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - regression_performance
      - num_target_drift
      - cat_target_drift
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 100
