# 4. Deployment cho Auth Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: chesaurieng/auth-service:0.0.1
        ports:
        - containerPort: 5001
        env:
          # Đảm bảo kết nối đến Cassandra được trỏ tới service của Cassandra trên AKS
          - name: CASSANDRA_HOST
            value: "cassandra"
          # Nếu muốn, bạn có thể override JWT_SECRET_KEY từ code (hoặc chuyển sang Secret)
          - name: JWT_SECRET_KEY
            value: "your-secret-key"
---
# 5. Service cho Auth Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP